
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.ncb
{
public partial class TbGlobal
{
    private readonly System.Collections.Generic.Dictionary<int, ncb.Global> _dataMap;
    private readonly System.Collections.Generic.List<ncb.Global> _dataList;
    
    public TbGlobal(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ncb.Global>();
        _dataList = new System.Collections.Generic.List<ncb.Global>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ncb.Global _v;
            _v = global::cfg.ncb.Global.DeserializeGlobal(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.TestCount, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ncb.Global> DataMap => _dataMap;
    public System.Collections.Generic.List<ncb.Global> DataList => _dataList;

    public ncb.Global GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ncb.Global Get(int key) => _dataMap[key];
    public ncb.Global this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

