
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.ncb
{
public partial class TbLanguage
{
    private readonly System.Collections.Generic.Dictionary<string, ncb.Language> _dataMap;
    private readonly System.Collections.Generic.List<ncb.Language> _dataList;
    
    public TbLanguage(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, ncb.Language>();
        _dataList = new System.Collections.Generic.List<ncb.Language>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ncb.Language _v;
            _v = global::cfg.ncb.Language.DeserializeLanguage(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, ncb.Language> DataMap => _dataMap;
    public System.Collections.Generic.List<ncb.Language> DataList => _dataList;

    public ncb.Language GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ncb.Language Get(string key) => _dataMap[key];
    public ncb.Language this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

