// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: msg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Msg {

  /// <summary>Holder for reflection information generated from msg.proto</summary>
  public static partial class MsgReflection {

    #region Descriptor
    /// <summary>File descriptor for msg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgltc2cucHJvdG8SA21zZyJPCgdTMkNfTXNnEhoKBGNvZGUYASABKA4yDC5t",
            "c2cuTXNnQ29kZRIXCgNtSWQYAiABKA4yCi5tc2cuTXNnSWQSDwoHbWVzc2Fn",
            "ZRgDIAEoCSrQAQoFTXNnSWQSCAoETlVMTBAAEg8KC01zZ19TMkNfTXNnEGQS",
            "FAoOVXNlcl9DMlNfTG9naW4QhI4GEhcKEVVzZXJfQzJTX1NhdmVEYXRhEIWO",
            "BhIaChRVc2VyX0MyU19SZXN0YXJ0R2FtZRCGjgYSGAoSVXNlcl9DMlNfV29y",
            "bGRSYW5rEIeOBhIUCg5Vc2VyX1MyQ19Mb2dpbhCkmwwSFwoRVXNlcl9TMkNf",
            "U2F2ZURhdGEQpZsMEhgKElVzZXJfUzJDX1dvcmxkUmFuaxCnmwwqJwoHTXNn",
            "Q29kZRIICgRTVUNDEAASEgoFRVJST1IQ////////////ASojCgxQbGF0Zm9y",
            "bVR5cGUSBgoCSDUQABILCgdXWF9NSU5JEAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Msg.MsgId), typeof(global::Msg.MsgCode), typeof(global::Msg.PlatformType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Msg.S2C_Msg), global::Msg.S2C_Msg.Parser, new[]{ "Code", "MId", "Message" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum MsgId {
    [pbr::OriginalName("NULL")] Null = 0,
    /// <summary>
    /// 回应协议
    /// </summary>
    [pbr::OriginalName("Msg_S2C_Msg")] MsgS2CMsg = 100,
    /// <summary>
    /// 登录
    /// </summary>
    [pbr::OriginalName("User_C2S_Login")] UserC2SLogin = 100100,
    [pbr::OriginalName("User_C2S_SaveData")] UserC2SSaveData = 100101,
    [pbr::OriginalName("User_C2S_RestartGame")] UserC2SRestartGame = 100102,
    [pbr::OriginalName("User_C2S_WorldRank")] UserC2SWorldRank = 100103,
    /// <summary>
    /// 登录返回
    /// </summary>
    [pbr::OriginalName("User_S2C_Login")] UserS2CLogin = 200100,
    [pbr::OriginalName("User_S2C_SaveData")] UserS2CSaveData = 200101,
    [pbr::OriginalName("User_S2C_WorldRank")] UserS2CWorldRank = 200103,
  }

  public enum MsgCode {
    /// <summary>
    /// 成功
    /// </summary>
    [pbr::OriginalName("SUCC")] Succ = 0,
    /// <summary>
    /// 失败
    /// </summary>
    [pbr::OriginalName("ERROR")] Error = -1,
  }

  public enum PlatformType {
    /// <summary>
    /// 本地
    /// </summary>
    [pbr::OriginalName("H5")] H5 = 0,
    /// <summary>
    /// 微信小游戏
    /// </summary>
    [pbr::OriginalName("WX_MINI")] WxMini = 1,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class S2C_Msg : pb::IMessage<S2C_Msg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<S2C_Msg> _parser = new pb::MessageParser<S2C_Msg>(() => new S2C_Msg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<S2C_Msg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Msg.MsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S2C_Msg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S2C_Msg(S2C_Msg other) : this() {
      code_ = other.code_;
      mId_ = other.mId_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S2C_Msg Clone() {
      return new S2C_Msg(this);
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 1;
    private global::Msg.MsgCode code_ = global::Msg.MsgCode.Succ;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Msg.MsgCode Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "mId" field.</summary>
    public const int MIdFieldNumber = 2;
    private global::Msg.MsgId mId_ = global::Msg.MsgId.Null;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Msg.MsgId MId {
      get { return mId_; }
      set {
        mId_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 3;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as S2C_Msg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(S2C_Msg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (MId != other.MId) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Code != global::Msg.MsgCode.Succ) hash ^= Code.GetHashCode();
      if (MId != global::Msg.MsgId.Null) hash ^= MId.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Code != global::Msg.MsgCode.Succ) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Code);
      }
      if (MId != global::Msg.MsgId.Null) {
        output.WriteRawTag(16);
        output.WriteEnum((int) MId);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Code != global::Msg.MsgCode.Succ) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Code);
      }
      if (MId != global::Msg.MsgId.Null) {
        output.WriteRawTag(16);
        output.WriteEnum((int) MId);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Code != global::Msg.MsgCode.Succ) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Code);
      }
      if (MId != global::Msg.MsgId.Null) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MId);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(S2C_Msg other) {
      if (other == null) {
        return;
      }
      if (other.Code != global::Msg.MsgCode.Succ) {
        Code = other.Code;
      }
      if (other.MId != global::Msg.MsgId.Null) {
        MId = other.MId;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Code = (global::Msg.MsgCode) input.ReadEnum();
            break;
          }
          case 16: {
            MId = (global::Msg.MsgId) input.ReadEnum();
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Code = (global::Msg.MsgCode) input.ReadEnum();
            break;
          }
          case 16: {
            MId = (global::Msg.MsgId) input.ReadEnum();
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
