
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.ncb
{
public sealed partial class Global : Luban.BeanBase
{
    public Global(ByteBuf _buf) 
    {
        TestCount = _buf.ReadInt();
    }

    public static Global DeserializeGlobal(ByteBuf _buf)
    {
        return new ncb.Global(_buf);
    }

    /// <summary>
    /// 测试
    /// </summary>
    public readonly int TestCount;
   
    public const int __ID__ = 317016964;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "TestCount:" + TestCount + ","
        + "}";
    }
}

}

